### ISSUE TITLE
FastVGICP doesn't support PointXYZINormal type point.

### ISSUE THREAD

**Issue by G4419** [koide3/fast_gicp#164]
when i use fast_gicp::FastVGICP<pcl::PointXYZINormal, pcl::PointXYZINormal> ,  undefined reference compilation error will occur. However, pcl::PointXYZI  doesn't report an error.

**Comment by koide3** [comment]
You need to add custom point types to the following codes to explicitly instantiate registration template classes.

https://github.com/koide3/fast_gicp/blob/master/src/fast_gicp/gicp/fast_gicp.cpp
https://github.com/koide3/fast_gicp/blob/master/src/fast_gicp/gicp/fast_vgicp.cpp

**Comment by G4419** [comment]
Thanks for your quick response; the problem's been fixed.
